#ifndef __APP_CONFIG_H__
#define __APP_CONFIG_H__

#define STRING_LENGTH_PIXEL 	32
#define STRING_LENGTH_COLOR		96
#define STRING_LENGTH_BITS		768

#define FRAME_BUFF_MINUS_ONE	767U

#define ACTIVE_SECTIONS 	8
#define WIDTH_PIXELS 		32

//#define USING_SIMULATOR
//#define USING_SIMULATOR_TOUCH

#define UART_BAUDRATE 460800

#endif
   