#ifndef __APP_CONFIG_H__
#define __APP_CONFIG_H__

#define STRING_LENGTH_PIXEL 	5
#define STRING_LENGTH_COLOR		15
#define STRING_LENGTH_BITS		120

#define INPUT_BUFF_MINUS_ONE	14U

#define ACTIVE_SECTIONS 	1
#define WIDTH_PIXELS 		32

#endif
